### ISSUE TITLE
Support Elasticsearch 7.x

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/scope#192]
Upgrade `elasticsearch-dsl` dependency, related code, install process and development environment to work with Elasticsearch 7.x.

**Comment by tw4l** [comment]
There seems to be an issue with Elasticsearch in the Docker development environment:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/src/search/management/commands/index_data.py", line 28, in handle
    index.delete(ignore=404)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch_dsl/index.py", line 405, in delete
    return self._get_connection(using).indices.delete(index=self._name, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 334, in delete
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 421, in perform_request
    _ProductChecker.raise_error(self._verified_elasticsearch)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 638, in raise_error
    raise UnsupportedProductError(message)
elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not a supported distribution of Elasticsearch
```
